# Exploración de conjuntos de datos

In [1]:
from huggingface_hub import login

login()

In [2]:
!hf auth whoami

user:  umoqnier
orgs:  ElotlMX,somosnlp-hackathon-2022,somosnlp,UNAMMexico

In [3]:
from datasets import load_dataset

## Mapuzugun to Spanish (arn-spa)

### Datasource: https://huggingface.co/datasets/mengct00/Mapudungun_iwslt26

In [4]:
MAPUZUGUN_TO_SPANISH = "mengct00/Mapudungun_iwslt26"

In [5]:
map_spa_data = load_dataset(MAPUZUGUN_TO_SPANISH, split="train", streaming=True)

Resolving data files:   0%|          | 0/121 [00:00<?, ?it/s]

In [9]:
data_subset = map_spa_data.take(3)

In [10]:
for i, example in enumerate(data_subset):
    print(f"Example {i}\n")
    audio = example["audio"]
    audio_array = audio["array"]  # shape: (T, )
    print("Audio arr", audio_array)
    sampling_rate = audio["sampling_rate"]
    assert sampling_rate == 44100

    transcript_raw = example["arn"]
    print("Transcript [RAW]", transcript_raw)
    transcript_clean = example["arn_clean"]
    print("Transcript [CLEAN]", transcript_clean)
    translation = example["spa"]
    print("Translation", translation)

Example 0

Audio arr [0.01184082 0.00787354 0.00668335 ... 0.06637573 0.06771851 0.0710144 ]
Transcript [RAW] Marimari lamngen ¿ini pingimi eymi?
Transcript [CLEAN] Marimari lamngen ¿ini pingimi eymi?
Translation Hola hermano, ¿cómo te llamas tú?
Example 1

Audio arr [0.0395813  0.0319519  0.0211792  ... 0.01953125 0.02087402 0.00814819]
Transcript [RAW] Marimari lamngen. Iñche tañi üy Agustin Kurikeo Kintrikeo pingey tañi üy. Iñche ñi mapu Kankura pingi. Feymu ta müli tañi chau, puke nuke, tañi peñi, tañi lamngen. Iñche tañi longko fey Jose <*SPA>sangre Mollfünao pingekefuy, tañi fütache fey kay. Femi tati lamngen.
Transcript [CLEAN] Marimari lamngen. Iñche tañi üy Agustin Kurikeo Kintrikeo pingey tañi üy. Iñche ñi mapu Kankura pingi. Feymu ta müli tañi chau, puke nuke, tañi peñi, tañi lamngen. Iñche tañi longko fey Jose sangre Mollfünao pingekefuy, tañi fütache fey kay. Femi tati lamngen.
Translation Hola hermana. Mi nombre Agustín Curiqueo Quintriqueo se dice mi nombre. Mi tierra se llama Cancura. Allí están mi papá, mis mamás, mi hermano, mi hermana. El principal de mi familia se llama José Sangre Mollfunao, mi viejo es ese pues. Así es pues, hermana.
Example 2

Audio arr [0.00286865 0.00250244 0.00463867 ... 0.03451538 0.03170776 0.03442383]
Transcript [RAW] <*SPA> Ya. Iñchekay, iñche üy fey pingen, iñche *feypingen, Maria Isabel Koñoepan, pingen iñche. Iñche fey tuwün Wapi Wapi *mapumu tuwün iñche, ñi tañi, tañi <uh> lof. Fey Kawemu pingi tañi lof, fey Kawemu pingi. Iñche fey <P> tamu fey <uh> Temuko mapu mülepan, mülepan ta, welu iñche ñi mapu fey üyüu müli Kawemu, wapi wap= Wapiche iñche.
Transcript [CLEAN] Ya. Iñchekay, iñche üy fey pingen, iñche *feypingen, Maria Isabel Koñoepan, pingen iñche. Iñche fey tuwün Wapi Wapi *mapumu tuwün iñche, ñi tañi, tañi lof. Fey Kawemu pingi tañi lof, fey Kawemu pingi. Iñche fey tamu fey Temuko mapu mülepan, mülepan ta, welu iñche ñi mapu fey üyüu müli Kawemu, wapi wap= Wapiche iñche.
Translation Ya. Yo también, mi nombre, me llamo yo soy llamada, María Isabel Coñoepán, me llamo yo. Mi procedencia es Huapi, De Huapi provengo yo, de mi, de mi comunidad. Mi sector se llama Cahuemu, Cahuemu se llama. Ahora estoy acá en Temuco, estoy aqui ahora, pero mi tierra está allá en Cahuemu, isla yo soy isleña.

## Bemba to English (bem-eng)

### Datasource:  https://github.com/csikasote/bigc

#### Extra datasources:

- ASR only - https://github.com/csikasote/BembaSpeech
- ASR and raw data - https://github.com/unza-speech-lab/zambezi-voice

In [8]:
import pandas as pd

In [16]:
bemba_data = pd.read_csv("https://raw.githubusercontent.com/csikasote/bigc/refs/heads/main/data/bem/datasheet.csv", sep="\t")

In [19]:
bemba_data.head()

,pair_id,image,sentence_id,image_id,audio_id,speaker_id,gender,duration,sample_rate,audio_format,recording_lang,native_lang,bem_transcription,en_translation
0,NaN,100_0,1,3720376242.jpg,100_0_01_210929-011719_bem_72c_elicit_0.wav,11,male,8.530,16000,vnd.wave,bem,bem,Ibumba lyabashitata nabeminina mumbali mumusebo,A group of men is standing on the roadside.
1,NaN,100_1,2,3720376242.jpg,100_1_02_210929-011803_bem_81c_elicit_0.wav,12,male,13.862,16000,vnd.wave,bem,bem,Ninshi bashitata aba bonse bakolonganina pamo ...,Why are all these men gathered in such a way? ...
2,NaN,100_2,1,3720376242.jpg,100_2_01_210929-011719_bem_72c_elicit_1.wav,11,male,10.663,16000,vnd.wave,bem,bem,"aba bashitata balelolela ukuculuka umusebo, ba...","They are waiting to cross the road, they are w..."
3,NaN,100_3,2,3720376242.jpg,100_3_02_210929-011803_bem_81c_elicit_1.wav,12,male,15.200,16000,vnd.wave,bem,bem,Nomba bambi bashitata tabalemoneka nokupoosa a...,They do not seem to be paying attention to wha...
4,NaN,100_4,1,3720376242.jpg,100_4_01_210929-011719_bem_72c_elicit_2.wav,11,male,17.061,16000,vnd.wave,bem,bem,"Endita, bonse balelwisho kuculuka, aba bambi a...","Yes, they are all trying to cross the road, th..."

In [26]:
for transcript in bemba_data.iloc[:10]["bem_transcription"]:
    print(transcript)

Ibumba lyabashitata nabeminina mumbali mumusebo
Ninshi bashitata aba bonse bakolonganina pamo mumusango wa waso? bushe finshi balelolela olo finshi balelweisho kucita?
aba bashitata balelolela ukuculuka umusebo, balelolela imyotoka shipite
Nomba bambi bashitata tabalemoneka nokupoosa amano kumusebo balemoneka fye nabena balifye mucalo fye icabo, bushe nibonse abalefwayo kulwisho abalelwisho ukuculuka umusebo uyu?
Endita, bonse balelwisho kuculuka, aba bambi abalemoneka abashipooseleko amano balelolesha uko balaiminikila imyotoka ishakubasenda
shikulubantu alelya mukabale kabuuta
shikulubantu wine alemoneka napoosa amano uko alelolesha, bushe ninshi cingalenga apoose so amano uko alelolesha?
Ali na bantu abo ekele nankwe pacipuna ebo alelanda nabo eko alelolesha
Ngako akalemoneka akabuuta akeminine pambale iilemoneka apo kumbali yakashikulu?
Ni kendo nga malaiti yaya eyo basanika ukukwato lubuuto

In [27]:
for transcript in bemba_data.iloc[:10]["en_translation"]:
    print(transcript)

A group of men is standing on the roadside.
Why are all these men gathered in such a way? What are they waiting for or what are they trying to do?
They are waiting to cross the road, they are waiting fo the vehicles to pass.
They do not seem to be paying attention to what's happening, they seem to be focused on something else, are they all trying to cross the road?
Yes, they are all trying to cross the road, the ones that do not seem to be paying attention are just trying to see where they can get vehicles to get on.
A man is eating from a white plate.
This man seems to be focused on where he is looking, why is he this focused?
He is sited with some people on the chairs, they are ones he is looking at.
What is that white thing standing on the plate that is beside him?
It is a candle that they lit up when there is power, they use it for light.

## Bhojpuri to Hindi (bho-hin)

### Datasource: https://github.com/shashwatup9k/iwslt2026_bho-hi

**NOTE:** I can't see any translations. Is this dataset ASR only (?)

In [4]:
import requests

response = requests.get("https://raw.githubusercontent.com/shashwatup9k/iwslt2026_bho-hi/refs/heads/main/iwslt2024-2025_bho-hi/dev/txt/dev.hi")
data = response.text.split("\n")

In [5]:
data[:5]

['ये आकाशवाणी गोरखपुर है .',
 'अब आप विकास राय से खबर सुन सकते हैं.',
 'देश ने COVID-19 टीकाकरण अभियान में 100 करोड़ रुपये से अधिक का लक्ष्य हासिल कर इतिहास रच दिया है',
 'आकाशवाणी उन डॉक्टरों, नर्सों और अन्य स्वास्थ्य कर्मियों को बधाई देता है जिन्होंने इस महत्वपूर्ण कार में योगदान दिया',
 'साथ ही, मैं आपको चेतावनी देना चाहूंगा कि COVID-19 अभी खत्म नहीं हुआ है']

## Central Kurdish to English (ckb-eng)

### Datasource: https://lium.univ-lemans.fr/en/corpus-commute-kurdish/

**NOTE:** We need to manually download the `.zip` file from https://lium.univ-lemans.fr/data-ext/iwslt2026/commute-kurdish-iwslt2026.zip

In [6]:
# TODO: Data exploration

## Irish to English (gle-eng)

TODO

## Igbo to English (ibo-eng)

TODO

## Quechua to Spanish (que-spa)

### Datasource: https://github.com/johneortega/IWSLT2026_Quechua_data

**NOTE:** Not sure what is the dataset suitable for *Constrained condition* (systems are trained only on the datasets provided by the organizers )

In [9]:
que_data = pd.read_csv("https://raw.githubusercontent.com/johneortega/IWSLT2026_Quechua_data/refs/heads/main/que_spa_synthetic_translation/train/txt/train.tsv", sep="\t")

In [10]:
que_data.head()

,path,speaker_id,offset,duration,que,spa
0,quechua_01071.wav,JORGE,0.0,5.51,sulpaykuykikum tayta mario mejía kay maytu ruw...,gracias señor mario mejía por este folleto
1,quechua_02672.wav,MARCOS,0.0,29.05,es nuevo código procesal penal dos bueno seis ...,es nuevo código procesal penal dos bueno seis ...
2,quechua_07287.wav,FELICIA,0.0,30.00,imaymanamanta panelmanta huk trabajo rurarikap...,varios paneles se hará un trabajo sobre esos y...
3,quechua_03506.wav,MARCOS,0.0,28.04,minka minkalla ayni aynilla yanapanakusun kusk...,minka minkalla ayni ayni ayni ayúdennos juntos...
4,quechua_04041.wav,MARCOS,0.0,27.04,hatun wañuyman hatun huchaman dios taytapa rey...,gran muerte gran pecado separación del reino d...

In [11]:
for transcript in que_data.iloc[:10]["que"]:
    print(transcript)

sulpaykuykikum tayta mario mejía kay maytu ruwasqaskirayku
es nuevo código procesal penal dos bueno seis vacantes seis abogados se requiere derecho civil seis liderazgo y transparencia seis ortografía y redacción seis etiqueta social seis abordaje a las victimas de violencia familiar y sexual seis cultura y física seis bueno chayta vacantes nin kaypin arí entonces chaynaqa ahh chaymanta kachkantaq codigo
imaymanamanta panelmanta huk trabajo rurarikapunqa chaykunamantawan carreteramanta chaykunamanta paykuna uyarichkanku napaykurikuni llapan uyarikkunata diez chunka horasta paykuna tomananku caserioman chaytan ñuqa willarikuyta munaskani panay kusami turay chayllachu karichkan napaykuchu pikunapaq napaykullinitaq llapan uyariqkunapaq doctor
minka minkalla ayni aynilla yanapanakusun kuskamanta willarinakusun arí wawqipaniykuna imaynallam imaynallam kaypiña kutirimunchik wawqipaniykuna kaymi kay programa sumaq ayñi radio andahuaylas wayra wasintakama chayayka
hatun wañuyman hatun huchaman dios taytapa reynonmanta rakisqa kayman aparquwanchik kaynaña aquhinaña kay pachapi runakunata solamente huk runapa huchan solamente huk huchalla y chaymi romanos capítulo seis versículo veinti tres niwanchik por cuanto todos pecaron estan destituidos de la gloria de dios imaynam
kay comunidad anchata mañarikurqayku hina arí kunanqa kayqa institucón pública kutipun nintaq hinallataq arí ancha sumaqta kayqa napaykurillaykutaq haqay ugel asangaro ñin maypichus pay chikaqa ancha sumaqta yanapaykuwanku kaypi ñin chikaqa paykunapaq ancha sumaq munay napaykuy maytaq kayqa chunka suqtayuq punchawta huntarichkanqaku kayqa huk watatawan maytaq paykunapaq chikaqa hinallataq arí kayqa qaperos arí waykurimuchkanqa nintaq ancha sumaqta paqarin
kay perú suyunchikpi kimsa tutamanta pichqa chunka yupayniyuqña napayku chikaqa runa masinchikkunapaq pikunachus suyarikamuchkanku hinantin kay karu llaqtakunapi allin punchaw kaychun maymanta waqyarikamuchkanki imam sutiyki buenos días wawqiy jaime buenos días paniy norma allin punchaw imaynalla wawqiy paulino allinllachu paqariykuchkanki kusikuy musuq wata kachun kusallata kusirikusun feliz año nuevo
chakra llamk'aqpas kuchurpariwaptinkuqa utqhaylla allinyarquspa huk hunt'asqa k'uykaman kutiyku huk k'uykamantaqa iskayman kimsaman ima rakikuyta atiyku
karqa manam chaynapi reykuna sasachakuypi tarikunanpaq kunanmi nehemias rey artajerjespa waqtanpi kachkan nehemiasmi manaraq rey artajerses mikuyta mikuykuchkaptinmi hina chay platonmanta nehemias mikuq primerota hinaptin iskay kimsa cucharata mikuykuptinñam hina chay platollamanta nehemiaspa
wawqipanikuna chaynallataq educación secundaria secundariapaqpas kachkan cabalchanpi wawqipanikuna superior arí kaypi kachkan sumaq librokuna sumaq librokuna warmachakunapaq kay primariapi kaqkunapaq secundaria kaqkunapaq hanaypiña superiorpi kaqkunapaq chaynallataq universitario chaykunawanpas kachkan sumasumaq kay kachkantaq librokuna kay sumaq medicinamanta medicina chaynallataq derechomanta ingeniería hinallataq computación

In [12]:
for transcript in que_data.iloc[:10]["spa"]:
    print(transcript)

gracias señor mario mejía por este folleto
es nuevo código procesal penal dos bueno seis vacantes seis abogados requeridos derecho civil seis liderazgo y transparencia seis ortografía y redacción seis etiqueta social seis trato a víctimas de violencia familiar y sexual seis cultura y físico seis bueno esa vacante dice aquí sí entonces ahh entonces también hay código
varios paneles se hará un trabajo sobre esos y el camino de los que están escuchando saludo a todos los oyentes diez diez beben por el pueblo que quiero decirle a mi hermana mi querida hermana eso es todo hay saludos para quien saludos a todos los oyentes doctor
minka minkalla ayni ayni ayni ayúdennos juntos digamos si mis hermanos como están como están de vuelta aquí mis hermanos y hermanas este es el programa hermosa ayni radio andahuaylas ondas que llegan
gran muerte gran pecado separación del reino de dios el padre nos ha llevado al mundo así el pecado de un solo hombre un solo pecado y eso es lo que nos dice romanos capítulo seis versículo veintitrés porque todos han pecado están privados de la gloria de dios cómo
esta comunidad preguntamos mucho como si ahora esta es una institucion publica atras y si muy lindo este es un saludo a ese ugel asangaro donde realmente nos ayuda aqui dice que son muy lindos saludos donde esto va a estar dieciséis dias esto es otro año donde estan de verdad y si esto es kaperos si estara cocinando dice que esta muy lindo mañana
son las tres de la mañana cincuenta numeros saludos a toda nuestra gente que esta esperando en todo el mundo buen dia desde donde llamas como te llamas buenos dias hermano jaime buen dia hermana norma buen dia como estas hermano paulino bueno mañana feliz año nuevo feliz año nuevo
Incluso si el granjero nos corta, nos recuperamos rápidamente y volvemos a ser un capullo completo y podemos dividirnos en dos o tres pedazos en lugar de un capullo.
no era para que los reyes estuvieran en problemas ahora nehemías está al lado del rey artajerjes nehemías es antes de que el rey artajerjes comiera la comida del plato nehemías comió primero y luego después comió unas cuantas cucharadas del mismo plato nehemías
hermanos y hermanas y la educacion secundaria para secundaria esta a caballo hermanos y hermanas superiores si aqui hay libros hermosos libros hermosos para niños de primaria para secundaria para superior y universidad con ellos tambien hay maravilloso esto hay libros para medicina maravillosa medicina y derecho ingenieria y informática

## Catalan to English (ca-en)

### datasource: https://github.com/rjzevallos/IWSLT_2026_Catalan_Dataset

**NOTE:** We need to download the repository and extract the data from the files.

**NOTE II:** Is data broken (?)

In [ ]:
!git clone https://github.com/rjzevallos/IWSLT_2026_Catalan_Dataset.git

In [13]:
!ls

datasets.ipynb		    LICENSE  pyproject.toml  uv.lock
IWSLT_2026_Catalan_Dataset  main.py  README.md

In [17]:
!tree IWSLT_2026_Catalan_Dataset

IWSLT_2026_Catalan_Dataset
├── ca_en_synthetic_translation
│   ├── train
│   │   ├── data-00000-of-00001.arrow
│   │   ├── dataset_info.json
│   │   └── state.json
│   └── val
│       ├── data-00000-of-00001.arrow
│       ├── dataset_info.json
│       └── state.json
└── README.md

4 directories, 7 files

In [20]:
BASE = "IWSLT_2026_Catalan_Dataset/ca_en_synthetic_translation"
data_files = {
    "train": f"{BASE}/train/data-00000-of-00001.arrow",
    "validation": f"{BASE}/val/data-00000-of-00001.arrow",
}

dataset = load_dataset("arrow", data_files=data_files)

ArrowInvalid: Not an Arrow file

In [33]:
import os
print(os.path.exists(data_files["train"]))
print(os.path.exists(data_files["validation"]))

True
True

In [34]:
import pyarrow.ipc as ipc

try:
    with open(data_files["train"], 'rb') as f:
        reader = ipc.open_file(f)
        print(reader.schema)
except Exception as e:
    print(f"Error: {e}")

Error: Not an Arrow file

In [35]:
with open(data_files["train"], 'rb') as f:
    header = f.read(1000)
    print(f"File header: {header}")

File header: b'version https://git-lfs.github.com/spec/v1\noid sha256:3693c7282568e9cb8b4f2340c41abc428fbaf9e68eebebe1b0fc46454a4eba64\nsize 288594520\n'

In [36]:
df = pd.read_feather(data_files["train"])

ArrowInvalid: Not a Feather V1 or Arrow IPC file

## Yoruba to English (yor-eng)

TODO